
server:
  port: 8081

topic:
  name: new-task

spring:
  kafka:
    consumer:
      group-id: "default"
#      bootstrap-servers: localhost:9092
#        #      ,localhost:9093
#        #      localhost:9094
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#
#    producer:
#      bootstrap-servers: localhost:9092
#          #      ,localhost:9093
#          #      localhost:9094
#      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:mysql://localhost:3307/taskprocesing?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  Jpa/Hibernate:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    properties:
      hibernate:
      format_sql: true












#spring:
#  profiles:
#    active: local
#server:
#  port: 8081
#
#---
#spring:
#  config:
#    activate:
#      on-profile: local
#  kafka:
#    template:
#      default-topic: new-topic
#    consumer:
#      bootstrap-servers: localhost:9092
##      ,localhost:9093
##      localhost:9094
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: tasks-events-listener-group
#    producer:
#      bootstrap-servers: localhost:9092
##      ,localhost:9093
##      localhost:9094
#      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  #Datasource
#  datasource:
#    url: jdbc:mysql://localhost:3306/taskprocesing?useUnicode=true&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
##  Jpa/Hibernate:
#  jpa:
#    open-in-view: false
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true